### ISSUE TITLE
Enhancement suggestion: Consider adding ngx_http_proxy_connect_module (makes Nginx a forward proxy)

### ISSUE THREAD

**Issue by fevangelou** [angristan/nginx-autoinstall#101]
Saved me hours from carefully making my own installer routine. Thank you for that.

I actually also baked in this module for Nginx https://github.com/chobits/ngx_http_proxy_connect_module which allows it to become a forward proxy supporting both HTTP and HTTPS connections (bare bones Nginx can only do HTTP).

You might want to consider bundling that module as well :)

Thanks for your work.

**Comment by angristan** [comment]
Feel free to PR this :)
