### ISSUE TITLE
Support HTTP/3

### ISSUE THREAD

**Issue by angristan** [angristan/nginx-autoinstall#105]
https://blog.cloudflare.com/experiment-with-http-3-using-nginx-and-quiche/
https://github.com/cloudflare/quiche/tree/master/extras/nginx#readme

**Comment by stathis** [comment]
Personally, I've built Nginx with many of the extensions also offered by nginx-autoinstall, and I believe that this would not be a good idea. Too much bloat from various libraries needed to run quiche like BoringSSL, Rust, etc.

Plus, HTTP/3 isn't really supported by anything _real_ at the moment.

I say don't include this.

**Comment by angristan** [comment]
I've successfully built it without much trouble:

```sh
root@xxxxx:~/nginx-1.16.1# nginx -V
nginx version: nginx/1.16.1
built by gcc 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
built with OpenSSL 1.1.0 (compatible; BoringSSL) (running with BoringSSL)
TLS SNI support enabled
configure arguments: --prefix=/root/nginx-1.16.1 --with-http_ssl_module --with-http_v2_module --with-http_v3_module --with-openssl=../quiche/deps/boringssl --with-quiche=../quiche --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx
```

Granted, it does require Rust and Go...

**Comment by stathis** [comment]
It's not about trouble, it's the bloat plus the memory & cpu overhead of running this code I'm concerned about.

Plus no browser actually supports it properly. Even Chrome Canary is unreliable with h2+quic99, reverts to h2 all the time.

**Comment by angristan** [comment]
Yes, that's why it would be optional in the script...
