### ISSUE TITLE
Line 122: Syntax error on unexpected word `done '

### ISSUE THREAD

**Issue by poldixd** [angristan/nginx-autoinstall#107]
I've updated the script to the latest version and I got this error when I run the script. So I deleted the whole script and cloned it again. The same error is shown.

```
user@server:~/nginx-autoinstall$ sudo ./nginx-autoinstall.sh 

Welcome to the nginx-autoinstall script.

What do you want to do?
   1) Install or update Nginx
   2) Uninstall Nginx
   3) Update the script
   4) Exit

Select an option [1-4]: 1
./nginx-autoinstall.sh: Zeile 122: Syntaxfehler beim unerwarteten Wort `done'
./nginx-autoinstall.sh: Zeile 122: `                    done'
```

OS: `Debian GNU/Linux 8 (jessie)`

**Comment by angristan** [comment]
Thank you, has been fixed by https://github.com/angristan/nginx-autoinstall/commit/d26408f1d31b7c791eeca9c32469db72b5afdc7d
