### ISSUE TITLE
quic doesn't work

### ISSUE THREAD

**Issue by hsie** [angristan/nginx-autoinstall#110]
I successfully installed nginx with quic on my vps, but when I enable only the quic, not http2, then I can't access the website, even though I have enabled the quic connction in chrome canary.

below is the output of nginx -V and my nginx configuration file, would appreciate it if anyone can help me to figure out what is wrong, thanks in advance!

**nginx version: nginx/1.16.1**

built by gcc 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
built with OpenSSL 1.1.0 (compatible; BoringSSL) (running with BoringSSL)
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --user=nginx --group=nginx --with-cc-opt=-Wno-deprecated-declarations --with-openssl=/usr/local/src/nginx/modules/quiche/deps/boringssl --with-quiche=/usr/local/src/nginx/modules/quiche --with-threads --with-file-aio --with-http_ssl_module --with-http_v2_module --with-http_mp4_module --with-http_auth_request_module --with-http_slice_module --with-http_stub_status_module --with-http_realip_module --with-http_sub_module --add-module=/usr/local/src/nginx/modules/incubator-pagespeed-ngx-1.13.35.2-stable --add-module=/usr/local/src/nginx/modules/ngx_brotli --with-http_v3_module

and the main configuration file of nginx.

server {
	listen 443 quic reuseport;
   	listen 443 ssl http2 fastopen=500;
	listen         [::]:443  ssl http2;
       	server_name www.sample.com sample.com;
	root /data/cccc;
	index index.php;
	ssl_certificate /etc/letsencrypt/rsa/sample.com/fullchain.cer;
	ssl_certificate_key /etc/letsencrypt/rsa/sample.com/sample.com.key;
	ssl_certificate /etc/letsencrypt/ecdsa/sample.com_ecc/fullchain.cer;
	ssl_certificate_key /etc/letsencrypt/ecdsa/sample.com_ecc/sample.com.key;
	ssl_session_timeout 1d;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_dhparam dhparam.pem;
	ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;                                          
	ssl_ciphers TLS13+AESGCM+AES128:EECDH+AES128;
	ssl_ecdh_curve X25519:P-256:P-384;
	ssl_prefer_server_ciphers on; 
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_early_data on;
	proxy_set_header Early-Data $ssl_early_data;
	ssl_buffer_size 4k;
	add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
	add_header X-Frame-Options deny;
	add_header X-XSS-Protection "1; mode=block";
	add_header alt-svc 'h3-23=":443"; ma=86400';

**Comment by TemhAAhmeT** [comment]
Are you sure 1.16 supports http/3?
I guess http/3 support starts with 1.17

**Comment by panpansh** [comment]
quic is working but not with pagespeed

**Comment by hsie** [comment]
> quic is working, 1.16 patch only (currently no 1.17: https://github.com/cloudflare/quiche/tree/master/extras/nginx ) but not with pagespeed and not with modsecurity. Any feedback ?

Thanks but even if I removed pagespeed and modsecurity module, it still doesn't work.

Always shows "NET::ERR_CERT_COMMON_NAME_INVALID"

**Comment by OptimBro** [comment]
Yes, it doesn't work, even if pagespeed module and modsec is disabled, even without any external modules, it doesn't work. Test fails on http3 checking tools too. If anyone gets a working http3, please share your configs.

I'll try in few days again.

Thanks

**Comment by SoftCreatR** [comment]
It works fine with the latest release of nginx-autoinstall. Make sure, that the UDP (not just TCP) port 443 is accessible and not blocked using a firewall (e.g. ufw).

**Comment by OptimBro** [comment]
Okay, I'll try today and will share feedback, if its working or not with the latest script.

**Comment by OptimBro** [comment]
QUIC is working, tested on 1.17.9 too

**Comment by angristan** [comment]
Thanks!
