### ISSUE TITLE
Brotli does not work

### ISSUE THREAD

**Issue by Angristan** [Angristan/nginx-autoinstall#12]
`objs/Makefile:1441: recipe for target 'objs/addon/src/ngx_http_brotli_filter_module.o' failed`

Will take a look ASAP.

**Comment by Wonderfall** [comment]
On m'avait rapporté la même chose, take a look : https://github.com/google/ngx_brotli/issues/39
Solution : https://github.com/google/ngx_brotli/issues/39#issuecomment-254093378

**Comment by Angristan** [comment]
Merci ! Je regarde ça demain.

**Comment by Angristan** [comment]
Fixed https://github.com/Angristan/nginx-autoinstall/commit/82347e83d33a7858bb02e6781d77ff1b1eb936c4
