### ISSUE TITLE
Nginx-autoinstall with let's encrypt certbot

### ISSUE THREAD

**Issue by Firzenizer** [angristan/nginx-autoinstall#124]
Any advice how to install let's encrypt certbot, when using nginx-autoinstall? AFAIK this is issue with APT that it thinks nginx is not installed. And installing from repositories is also blocked after using nginx-autoinstall.

```
apt-get install certbot python-certbot-nginx
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-certbot-nginx : Depends: python3-certbot-nginx but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

It seems I was able to get around this issue installing nginx using apt then installing certbot. After that installing using nginx-autoinstall. I just wonder, if this method will be giving me hard time with apt in the future.

**Comment by angristan** [comment]
Yeah you should really not have nginx installed from apt along with nginx-autoinstall.

You should be able to install certbot without APT: https://certbot.eff.org/lets-encrypt/pip-nginx

**Comment by Firzenizer** [comment]
I think I got it working now. Removed certbot and all nginx installations. Then installed using nginx-autoinstall and installed certbot using pip.
