### ISSUE TITLE
Installation fails 

### ISSUE THREAD

**Issue by stinger-forever** [angristan/nginx-autoinstall#126]
It's not possible to compile Nginx 1.17.9 with modsecurity on ubuntu 16.04
I had to edit LIBMAXMINDDB_VER=1.3.2 to LIBMAXMINDDB_VER=1.4.2 to fix the issue. 
Overall Script working great!

**Comment by angristan** [comment]
Ok thanks, seem to work on Debian 10 but not Ubuntu 16.04

**Comment by stinger-forever** [comment]
Also for Ubuntu 16.04 some prerequisites ( not sure which one exactly ) are missing and it leads to modsecurity compilation failures. 
As workaround I used the following maybe it will be useful for someone, so I close the issue: 

apt-get install apache2-dev autoconf automake build-essential bzip2 checkinstall devscripts flex g++ gcc git graphicsmagick-imagemagick-compat graphicsmagick-libmagick-dev-compat libaio-dev libaio1 libass-dev libatomic-ops-dev libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavutil-dev libbz2-dev libcdio-cdda1 libcdio-paranoia1 libcdio13 libcurl4-openssl-dev libfaac-dev libfreetype6-dev libgd-dev libgeoip-dev libgeoip1 libgif-dev libgpac-dev libgsm1-dev libjack-jackd2-dev libjpeg-dev libjpeg-progs libjpeg8-dev liblmdb-dev libmp3lame-dev libncurses5-dev libopencore-amrnb-dev libopencore-amrwb-dev libpam0g-dev libpcre3 libpcre3-dev libperl-dev libpng12-dev libpng12-0 libpng12-dev libreadline-dev librtmp-dev libsdl1.2-dev libssl-dev libssl1.0.0 libswscale-dev libtheora-dev libtiff5-dev libtool libva-dev libvdpau-dev libvorbis-dev libxml2-dev libxslt-dev libxslt1-dev libxslt1.1 libxvidcore-dev libxvidcore4 libyajl-dev make openssl perl pkg-config tar texi2html unzip zip zlib1g-dev
