### ISSUE TITLE
Install on CentOS?

### ISSUE THREAD

**Issue by victoriusnet** [angristan/nginx-autoinstall#127]
Hi guys,

I know this script is not for CentOS, but I would give it a try on CentOS 8 by installing all the dependencies which would be installed by apt-get. 

I got everything right except the starting: 

-- Unit nginx.service has begun starting up.
Mar 25 13:33:40 host20 systemd[29155]: nginx.service: Failed to execute command: No such file or direct>
Mar 25 13:33:40 host20 systemd[29155]: nginx.service: Failed at step EXEC spawning /usr/sbin/nginx: No >
-- Subject: Process /usr/sbin/nginx could not be executed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- The process /usr/sbin/nginx could not be executed and failed.
--
-- The error number returned by this process is 2.

Any idea why /usr/sbin/nginx does not exists?

Thank you!

**Comment by victoriusnet** [comment]
Update: make install failed with: usr/local/src/nginx/modules/quiche/deps/boringssl/.openssl/include/openssl/stack.h: In function ‘int sk_OPENSSL_STRING_call_cmp_func(stack_cmp_func, const void**, const void**)’:
/usr/local/src/nginx/modules/quiche/deps/boringssl/.openssl/include/openssl/stack.h:298:41: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]

and errors on other files connecting to BoringSSL

**Comment by randomshell** [comment]
Adding support to CentOS can be a feature, but I don't think BoringSSL will be supported. Their README says:
```
Although BoringSSL is an open source project, it is not intended for general use, as OpenSSL is.
We don't recommend that third parties depend upon it.
Doing so is likely to be frustrating because there are no guarantees of API or ABI stability.
```

**Comment by randomshell** [comment]
Add `--with-cc-opt=-Wno-ignored-qualifiers` to the `./configure` command and compile again. Thanks @shirtjs

@angristan supporting CentOS could be an enhancement?

**Comment by angristan** [comment]
If someone want to add CentOS support, be my guest
