### ISSUE TITLE
GeoIP needs account to download

### ISSUE THREAD

**Issue by victoriusnet** [angristan/nginx-autoinstall#128]
Starting December 30, 2019, downloads will no longer be served from our public GeoLite2 page, from geolite.maxmind.com/download/geoip/database/*, or from any other public URL.

https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

--2020-03-25 13:50:35--  https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz
Resolving geolite.maxmind.com (geolite.maxmind.com)... failed: Name or service not known.
wget: unable to resolve host address ‘geolite.maxmind.com’
--2020-03-25 13:50:35--  https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
Resolving geolite.maxmind.com (geolite.maxmind.com)... failed: Name or service not known.
wget: unable to resolve host address ‘geolite.maxmind.com’
tar: GeoLite2-City.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: GeoLite2-Country.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mkdir: cannot create directory ‘/opt/geoip’: File exists
/home/kallai/nginx-autoinstall.sh: line 240: cd: GeoLite2-City_*/: No such file or directory
mv: cannot stat 'GeoLite2-City.mmdb': No such file or directory
/home/kallai/nginx-autoinstall.sh: line 243: cd: GeoLite2-Country_*/: No such file or directory
mv: cannot stat 'GeoLite2-Country.mmdb': No such file or directory

**Comment by randomshell** [comment]
From https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/
> We will continue to offer the GeoLite2 databases without charge, and with the ability to redistribute with proper attribution and in compliance with privacy regulations.

They can be redistributed for free once downloaded.
@angristan maybe we can ask if the user wants to use the official download url with his key or download them for free from mirror like https://github.com/P3TERX/GeoLite.mmdb. For security reasons the files can be hosted in this repo though.

**Comment by randomshell** [comment]
There is https://db-ip.com/db/lite.php too but they want attribution on the web pages.

**Comment by angristan** [comment]
This isn't good news :(

**Comment by skid9000** [comment]
Theses guys are driving me nuts, can't event have a proper database with dual stack IPv4 and IPv6...

I think we should just remove the auto-dl and let a message to the user to how to download their crap and where to put it.

**Comment by SoftCreatR** [comment]
RIPE/ARIN don't provide accurate informations, that's the problem.

**Comment by skid9000** [comment]
Well if we take RIR databases, we have for an IP : 
- ASN
- ORG
- Country
- City in some cases

If we compare to GeoLite that's pretty much the same... Except that you don't have a database to update yourself every now and then.

**Comment by SoftCreatR** [comment]
Well, even if you are right, it's a huge difference, if you query an external database, or a self hosted one. Just one word: GDPR

**Comment by skid9000** [comment]
Hm, i see your point.
But tbh associating ip related information + ip with user information don't fall under GDPR already anyway ?
I mean that when you must be transparent about how you collect data about the user with his consent, if that's Maxmind (even self hosted) or a RIR database, shouldn't it be mentioned in the ToS/Privacy Policy as how you guessed the City of your last session for example ?

# That's off topic with the initial subject of the issue, but i think it deserve some thoughts  #

**Comment by SoftCreatR** [comment]
At least, here it's a little bit different. You have to mention, that you collect the IP address, but not, that you guess the location, except if you provide the IP address to a 3rd party to get the estimated location. However, I would still prefer using maxmind, if there's a way. I'll look at it, when I find some time.

**Comment by randomshell** [comment]
@angristan if you are ok with including the attribution in the readme we can mirror it here or in another repository. They want:
```
This product includes GeoLite2 data created by MaxMind, available from
[https://www.maxmind.com](https://www.maxmind.com).
```
See https://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by Cave-Johnson** [comment]
Another option would be to add the "geoipupdate" tool (https://github.com/maxmind/geoipupdate) as part of the install but this would require a valid license key

**Comment by ponasromas** [comment]
Workaround on this still unresolved, critical problem is just to disable the libMaxMind dependency using `--with-maxmind=no` in the script.

**Comment by angristan** [comment]
Closed by https://github.com/angristan/nginx-autoinstall/pull/234
