### ISSUE TITLE
Latest config won't work on Ubuntu 16.04 (Amazon EC2)

### ISSUE THREAD

**Issue by TechLabs2beyond** [Angristan/nginx-autoinstall#13]
root@ip-172-31-3-187:~# ./nginx-autoinstall.sh

Welcome to the nginx-autoinstall script.

What do you want to do?
   1) Install or update Nginx
   2) Uninstall Nginx
   3) Update the script

Select an option [1-3]: 1

This script will install Nginx 1.10.1 (mainline) with some optional famous modul

Please tell me which modules you want to install.
If you select none, Nginx will be installed with its default modules.

Modules to install :
       PageSpeed 1.11.33.4 [y/n]: y
       Brotli [y/n]: y
       Headers More 0.32 [y/n]: y
       GeoIP [y/n]: y

Choose your OpenSSL implementation :
   1) System's OpenSSL (default)
   2) OpenSSL 1.0.2h from source
   3) LibreSSL 2.4.4 from source

Select an option [1-3]: 1

Nginx is ready to be installed, press any key to continue...

       Installing dependencies        [OK]
       Downloading ngx_pagespeed      [OK]
       Downloading libbrotli          [OK]
       Configuring libbrotli          [OK]
       Compiling libbrotli            [OK]
       Installing libbrotli           [OK]
       Downloading ngx_brotli         [OK]
       Downloading ngx_headers_more   [OK]
       Downloading GeoIP databases    [OK]
       Downloading Nginx              [OK]
       **Configuring Nginx              [FAIL]**

**Comment by Angristan** [comment]
> Automatically compile from source and install Nginx mainline, on **Debian 8**

https://github.com/Angristan/nginx-autoinstall/blob/master/README.md
