### ISSUE TITLE
Add support for ngx_http_substitutions_filter_module

### ISSUE THREAD

**Issue by shirt-dev** [angristan/nginx-autoinstall#130]
Could support for https://github.com/yaoweibin/ngx_http_substitutions_filter_module be added?

**Comment by angristan** [comment]
Does it work? The repo shows no commits since 2015.

**Comment by shirtjs** [comment]
Despite it not having been updated since 2015, it still works.

**Comment by angristan** [comment]
OK! Thanks. I likely won't have the time to implement this myself, but I'll gladly accept a PR. 🙂
