### ISSUE TITLE
Lua installation failed to compile

### ISSUE THREAD

**Issue by maulvi** [angristan/nginx-autoinstall#137]
my system:
Ubuntu 16.04 OpenVZ

I tried to only install nginx and lua modules other modules is working just fine, the Installation show success but cant start the nginx process because it's failed to compile at this part

`checking for LuaJIT library in /usr/local/lib/ and /usr/local/include/luajit-2.1/ (specified by the LUAJIT_LIB and LUAJIT_INC env, with -ldl) ... found
checking for LuaJIT 2.x ... not found
    ./configure: error: unsupported LuaJIT version; ngx_http_lua_module requires LuaJIT 2.x.
make: *** No rule to make target 'build', needed by 'default'.  Stop.
make: *** No rule to make target 'install'.  Stop.`

`if [[ "$LUA" = 'y' ]]; then
			
export LUAJIT_LIB=/usr/local/lib/
 			
export LUAJIT_INC=/usr/local/include/luajit-2.1/
		fi`

so I checking with ` ls /usr/local/include/luajit-2.1/` but required folder is not found.

**Comment by webr00t** [comment]
+1
