### ISSUE TITLE
Automatic checking of latest versions

### ISSUE THREAD

**Issue by Cave-Johnson** [angristan/nginx-autoinstall#143]
It'd be good to implement some form of checking for the latest version numbers of software/modules in to the script (it would also then require less maintenance from yourself) 

An example for nginx :
`latestVerNginx=$(curl -s 'https://nginx.org/en/download.html' | sed 's/</\'$'\n''</g' | sed -n '/>Stable version$/,$ p' | egrep -m1 -o '/download/nginx-.+\.tar\.gz')`

**Comment by angristan** [comment]
https://github.com/angristan/nginx-autoinstall/issues/88
