### ISSUE TITLE
Add Support for Nginx-provided http modules

### ISSUE THREAD

**Issue by kennyparsons** [angristan/nginx-autoinstall#145]
I reviewed the code, so I apologize if I missed it, but is it possible to specify the additional of nginx-provided http modules? Such as the [ngx_http_geoip_module](https://nginx.org/en/docs/http/ngx_http_geoip_module.html) or the [ngx_http_addition_module](https://nginx.org/en/docs/http/ngx_http_addition_module.html)? These modules are not third-party modules. They are ones provided by nginx that say 

> This module is not built by default, it should be enabled with the --with-http_addition_module configuration parameter.

I'd be glad to add these myself to the script. Would i just put the text after "NGINX_MODULES" on line 346?

**Comment by SoftCreatR** [comment]
> I'd be glad to add these myself to the script. Would i just put the text after "NGINX_MODULES" on line 346?

Yep. However, GeoIP is there.
