### ISSUE TITLE
Nginx Not Working

### ISSUE THREAD

**Issue by ferdikucuk** [angristan/nginx-autoinstall#152]
Hi, İnstall scripting but nginx not started

-- Unit nginx.service has begun starting up.
Jul 15 09:05:25 ferdi systemd[30877]: nginx.service: Failed to execute command: No such file or directory
Jul 15 09:05:25 ferdi systemd[30877]: nginx.service: Failed at step EXEC spawning /usr/sbin/nginx: No such file or directory
-- Subject: Process /usr/sbin/nginx could not be executed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The process /usr/sbin/nginx could not be executed and failed.
--
-- The error number returned by this process is 2.
Jul 15 09:05:25 ferdi systemd[1]: nginx.service: Control process exited, code=exited status=203
Jul 15 09:05:25 ferdi systemd[1]: nginx.service: Failed with result 'exit-code'.
Jul 15 09:05:25 ferdi systemd[1]: Failed to start A high performance web server and a reverse proxy server.

**Comment by UpperCenter** [comment]
2nd this, can confirm the same issue on Ubuntu 20.4
![image](https://user-images.githubusercontent.com/46819924/87539656-32ecdf80-c696-11ea-909f-6c1a441ebf99.png)
I would include the logs, but `cat /tmp/nginx-autoinstall.log` doesn't exist for me.

Running Ubuntu 20.04 LTS on kernel `5.4.0-40-generic`

**Comment by angristan** [comment]
- There is not log file. Everything is displayed on the output during the install
- Please do tell what settings you chose during the install
