### ISSUE TITLE
lua-nginx-module messes with nginx binary path (/usr/sbin/nginx: No such file or directory)

### ISSUE THREAD

**Issue by stevenmunro** [Angristan/nginx-autoinstall#156]
Experiencing same issue as [#152](152) **/usr/sbin/nginx: No such file or directory**

On Ubuntu 18.04.5, I ran the `./nginx-autoinstall.sh` script with the following selection;

Mainline 1.19.2

PageSpeed 1.13.35.2 [y/n]: **n**
Brotli [y/n]: **y**
Headers More 0.33 [y/n]: **y**
GeoIP [y/n]: **n**
Fancy index [y/n]: **n**
ngx_cache_purge [y/n]: **y**
ngx_http_lua_module [y/n]: **y**
nginx WebDAV [y/n]: **n**
nginx VTS [y/n]: **y**
nginx testcookie [y/n]: **n**
HTTP/3 (by Cloudflare, WILL INSTALL BoringSSL, Quiche, Rust and Go) [y/n]: **y**
nginx ModSecurity [y/n]: **n**
Cloudflare's TLS Dynamic Record Resizing patch [y/n]: **y**

I found the missing `nginx` file in `/usr/local/sbin/ .. ?` (can't remember exactly which folder after that) and moved that into `/usr/sbin/`, then `service nginx status` reported missing files to do with `lua`.

I re-ran the install script, choosing the uninstall option, and then again with the options above **without** `ngx_http_lua_module`. This time nginx is now working.

Hope this helps narrow down the issue.

**Comment by L422Y** [comment]
i am also seeing similar issues on ubuntu 20.04

**Comment by angristan** [comment]
@L422Y what options did you choose? Did you see anything in the install log?

**Comment by MaximeMichaud** [comment]
> @L422Y what options did you choose? Did you see anything in the install log?

Probably with HTTP/3

For my part, 20.04 is working with :

PageSpeed
Headers
Brotli
ModSecurity
Default OpenSSL

**Comment by aponkralnet** [comment]
+ 1

**Comment by cmersinli** [comment]
i have same issue on ubuntu 20.04

**Comment by mtx-z** [comment]
Same issue on Debian 10
