### ISSUE TITLE
Option in menu to enable logs

### ISSUE THREAD

**Issue by Angristan** [Angristan/nginx-autoinstall#16]

**Comment by novakin** [comment]
Having another option is a bad idea. Logs should be always enabled. Can be easily achieved by replacing 

`&>/dev/null`

by 

`2>> /tmp/script-error.log 1>> /tmp/script-output.log`

**Comment by novakin** [comment]
Glad you did as I suggested. 

Too much options kill the option

**Comment by Angristan** [comment]
Indeed, thank you
