### ISSUE TITLE
Compilation error: ‘ngx_listening_t’ {aka ‘struct ngx_listening_s’} has no member named ‘post_accept_timeout’

### ISSUE THREAD

**Issue by GwynethLlewelyn** [angristan/nginx-autoinstall#195]
Compilation fails under Ubuntu 20.04.2 LTS (both on nginx stable 1.20.1 and mainline 1.21.0), probably due to https://github.com/nginx/nginx/commit/2ec8fac2d6b8e5023c9894d10bc50d78e63f242c#diff-9450eecd83e011923d6b4cea72d7fc91b3bfaa924fb65e12de9d9d2511b202b6

```log
src/http/ngx_http_request.c:364:40: error: ‘ngx_listening_t’ {aka ‘struct ngx_listening_s’} has no member named ‘post_accept_timeout’
  364 |         ngx_add_timer(rev, c->listening->post_accept_timeout);
      |                                        ^~
src/http/ngx_http_request.c: In function ‘ngx_http_quic_handshake’:
src/http/ngx_http_request.c:1147:44: error: ‘ngx_listening_t’ {aka ‘struct ngx_listening_s’} has no member named ‘post_accept_timeout’
 1147 |             ngx_add_timer(rev, c->listening->post_accept_timeout);
      |
```

I've come across modules not compiling because of this error, see: https://github.com/winshining/nginx-http-flv-module/issues/205 (a different module, but same problem)

Usually, the fix is simple, e.g. just manually remove the line that sets up the timer (allegedly, the timer default is now 1 second, see the above-mentioned commit message); I've not tested that approach yet, but once I do it, I'll post the results here...

**Comment by GwynethLlewelyn** [comment]
Some good news: PR #192 seems to fix the above error for me. If that PR gets approved & merged, I'd say that this issue could be safely closed!

**Comment by GwynethLlewelyn** [comment]
So, any news on merging PR #192? `nginx` mainline has been bumped to 1.21.2 but I still have the same issue as mentioned on July 7 😞

I see that there are a few new commits here, but, AFAIK, not this fix...

**Comment by angristan** [comment]
Merged :)
