### ISSUE TITLE
can't install quic

### ISSUE THREAD

**Issue by hsie** [angristan/nginx-autoinstall#218]
when chooing to install quic, the following error happens, if not choosing quic, everything works well. would appreciate it if someone can help to clarify, thanks in advance!

patching file src/http/v2/ngx_http_v2_table.c
./configure: error: invalid option "--with-quiche=/usr/local/src/nginx/modules/quiche"
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.

**Comment by rhymeswithmogul** [comment]
It looks like the HTTP/3 patch got changed upstream.  Not sure how to proceed, either, but using an older version of the script doesn't work.

**Comment by bastakka** [comment]
Should be resolved now
