### ISSUE TITLE
http_ssl_module is missing

### ISSUE THREAD

**Issue by leo-coco** [Angristan/nginx-autoinstall#28]
Bonjour,

Voici le output de nginx -V

ginx version: nginx/1.13.1
built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
configure arguments: --add-module=/home/leo/ngx_brotli --add-module=/home/leo/ngx_pagespeed-1.12.34.2-beta --add-module=/home/leo/nginx_accept_language_module-master --with-openssl=/home/gregory/nginx/openssl-1.1.0e --prefix=/usr/local/share/nginx --conf-path=/etc/nginx/nginx.conf --with-http_v2_module --with-http_gzip_static_module --sbin-path=/usr/local/sbin --error-log-path=/var/log/nginx/error.log

Le module http_ssl_module est manquant malgres sa presence dans la configuration du script. Que faire ?

**Comment by Angristan** [comment]
:) ...

![screenshot_23-06-2017_12-55-41](https://user-images.githubusercontent.com/11699655/27479217-49ddc53c-5813-11e7-93f7-307e8ba8050b.png)

No problem on Debian, sorry !
