### ISSUE TITLE
Option to compile with `http_uwsgi_module`

### ISSUE THREAD

**Issue by nirfse** [Angristan/nginx-autoinstall#32]
Please consider adding option for compiling with `http_uwsgi_module`, by default script has `--without-http_uwsgi_module` argument. Since I use nginx with `uwsgi_pass` I have to remember to manually edit the script after each update. Thank you!

**Comment by Angristan** [comment]
Hi, I won't since I don't think it's used much, but you can use a simple command like 
`sed -i 's|without-http_uwsgi_module|with-http_uwsgi_module|' nginx-autoinstall.sh` after every update.
