### ISSUE TITLE
Compile Nginx Error

### ISSUE THREAD

**Issue by Eckybrazzz** [Angristan/nginx-autoinstall#34]
Hi,

The compiling of Nginx does not complete.

output /tmp/nginx-autoinstall-error.log
2017-08-11 18:40:39 (735 MB/s) - ‘nginx.conf’ saved [1800/1800]

--2017-08-11 18:40:39--  https://raw.githubusercontent.com/cloudflare/sslconfig/master/patches/nginx__1.11.5_dynamic_tls_records.patch
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.56.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.56.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8243 (8.0K) [text/plain]
Saving to: ‘nginx__1.11.5_dynamic_tls_records.patch’

     0K ........                                              100%  138M=0s

2017-08-11 18:40:40 (138 MB/s) - ‘nginx__1.11.5_dynamic_tls_records.patch’ saved [8243/8243]

/usr/local/src/ngx_pagespeed-1.12.34.2-stable/src/ngx_pagespeed.cc: In function ‘ngx_int_t net_instaweb::{anonymous}::ps_preaccess_handler(ngx_http_request_t*)’:
/usr/local/src/ngx_pagespeed-1.12.34.2-stable/src/ngx_pagespeed.cc:3011:31: error: ‘ngx_http_core_try_files_phase’ was not declared in this scope
   while (ph[i + 1].checker != ngx_http_core_try_files_phase &&
                               ^
make[1]: *** [objs/addon/src/ngx_pagespeed.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [build] Error 2

**Comment by Angristan** [comment]
There is indeed a problem with Pagespeed and Nginx 1.13.4. It's out of my control so please use Nginx 1.13.3 or 1.12.1 (stable).
