### ISSUE TITLE
Compiling error.  Please set Nginx 1.13.3 or 1.12.1 (stable). on the site

### ISSUE THREAD

**Issue by Eckybrazzz** [Angristan/nginx-autoinstall#35]
Compiling error.  Please set Nginx 1.13.3 or 1.12.1 (stable). on the site until the issue is resolved.

Thanks,

Mike

**Comment by Angristan** [comment]
You can edit the script, the versions are set at the beginning : https://github.com/Angristan/nginx-autoinstall/blob/master/nginx-autoinstall.sh#L15
