### ISSUE TITLE
Compiling nginx failed

### ISSUE THREAD

**Issue by Firzenizer** [Angristan/nginx-autoinstall#37]
Compiling failing on clean Debian 9. Tried to install nginx with pagespeed and brotli using system openssl.

## Options selected
> Modules to install :
>        PageSpeed 1.12.34.2 [y/n]: y
>        Brotli [y/n]: y
>        Headers More 0.32 [y/n]: n
>        GeoIP [y/n]: n
>        Cloudflare's TLS Dynamic Record Resizing patch [y/n]: n
> 
> Choose your OpenSSL implementation :
>    1) System's OpenSSL (1.1.0f)
>    2) OpenSSL 1.1.0f from source
>    3) LibreSSL 2.6.0 from source
> 
> Select an option [1-3]: 1
> 
> Nginx is ready to be installed, press any key to continue...
> 
>        Installing dependencies        [OK]
>        Downloading ngx_pagespeed      [OK]
>        Downloading libbrotli          [OK]
>        Configuring libbrotli          [OK]
>        Compiling libbrotli            [OK]
>        Installing libbrotli           [OK]
>        Downloading ngx_brotli         [OK]
>        Downloading Nginx              [OK]
>        Configuring Nginx              [OK]
>        Compiling Nginx                [FAIL]

## Log
> 2017-08-31 06:53:15 (12.2 MB/s) - ‘1.12.34.2-x64.tar.gz’ saved [16968086/16968086]
> 
> rm: cannot remove 'libbrotli': No such file or directory
> Cloning into 'libbrotli'...
> Submodule 'brotli' (https://github.com/google/brotli) registered for path 'brotli'
> Cloning into '/usr/local/src/libbrotli/brotli'...
> configure.ac:7: installing './compile'
> configure.ac:7: installing './config.guess'
> configure.ac:7: installing './config.sub'
> configure.ac:8: installing './install-sh'
> configure.ac:8: installing './missing'
> Makefile.am: installing './depcomp'
> ar: `u' modifier ignored since `D' is the default (see `U')
> ar: `u' modifier ignored since `D' is the default (see `U')
> rm: cannot remove 'ngx_brotli': No such file or directory
> Cloning into 'ngx_brotli'...
> Submodule 'deps/brotli' (https://github.com/google/brotli.git) registered for path 'deps/brotli'
> Cloning into '/usr/local/src/ngx_brotli/deps/brotli'...
> rm: cannot remove '/usr/local/src/nginx-*': No such file or directory
> --2017-08-31 06:54:40--  https://raw.githubusercontent.com/Angristan/nginx-autoinstall/master/conf/nginx.conf
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 1800 (1.8K) [text/plain]
> Saving to: ‘nginx.conf’
> 
>      0K .                                                     100% 46.1M=0s
> 
> 2017-08-31 06:54:40 (46.1 MB/s) - ‘nginx.conf’ saved [1800/1800]
> 
> /usr/local/src/ngx_pagespeed-1.12.34.2-stable/src/ngx_pagespeed.cc: In function ‘ngx_int_t net_instaweb::{anonymous}::ps_preaccess_handler(ngx_http_request_t*)’:
> /usr/local/src/ngx_pagespeed-1.12.34.2-stable/src/ngx_pagespeed.cc:3011:31: error: ‘ngx_http_core_try_files_phase’ was not declared in this scope
>    while (ph[i + 1].checker != ngx_http_core_try_files_phase &&
>                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> make[1]: *** [objs/addon/src/ngx_pagespeed.o] Error 1
> make: *** [build] Error 2

**Comment by Firzenizer** [comment]
It seems the newest nginx version 1.13.4 does that.
https://github.com/pagespeed/ngx_pagespeed/issues/1451
I switched to newest stable 1.12.1 and everything worked just fine. A comment in the issue above also suggested that using 1.13.3 works.

**Comment by Angristan** [comment]
Yes, you have to use an older version of Nginx or wait for a new version of Pagespeed.
