### ISSUE TITLE
Not found link with pagespeed

### ISSUE THREAD

**Issue by Pavel-Novikov** [Angristan/nginx-autoinstall#43]
Debian 9 64:
Nginx is ready to be installed, press any key to continue...

       Installing dependencies        [OK]
./nginx-autoinstall.sh: line 130: cd: ngx_pagespeed-1.12.34.3-stable: No such file or directory
rm: cannot remove '.tar.gz': No such file or directory
       Downloading ngx_pagespeed      [FAIL]

Please look /tmp/nginx-autoinstall-error.log

root@deb9:~# cat /tmp/nginx-autoinstall-error.log

rm: cannot remove 'ngx_pagespeed-*-stable': No such file or directory
--2018-01-09 04:46:04--  https://github.com/pagespeed/ngx_pagespeed/archive/v1.12.34.3-stable.zip
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/apache/incubator-pagespeed-ngx/archive/v1.12.34.3-stable.zip [following]
--2018-01-09 04:46:05--  https://github.com/apache/incubator-pagespeed-ngx/archive/v1.12.34.3-stable.zip
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/apache/incubator-pagespeed-ngx/zip/v1.12.34.3-stable [following]
--2018-01-09 04:46:05--  https://codeload.github.com/apache/incubator-pagespeed-ngx/zip/v1.12.34.3-stable
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘v1.12.34.3-stable.zip’

     0K .......... .......... .......... .......... ..........  181K
    50K .......... .......... .......... .......... ..........  369K
   100K .......... .......... .......... .......... .....      5.76M=0.4s

2018-01-09 04:46:06 (347 KB/s) - ‘v1.12.34.3-stable.zip’ saved [148593]

--2018-01-09 04:46:06--  https://dl.google.com/dl/page-speed/psol/.tar.gz
Resolving dl.google.com (dl.google.com)... 172.217.16.46, 2a00:1450:401b:805::200e
Connecting to dl.google.com (dl.google.com)|172.217.16.46|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-01-09 04:46:06 ERROR 404: Not Found.

tar (child): .tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by Angristan** [comment]
Thanks for reporting this, I can't believe it's broken since https://github.com/Angristan/nginx-autoinstall/commit/700469a908f36eaff33df0feeb7ac779a28239c0...

**Comment by Angristan** [comment]
Also fixed in https://github.com/Angristan/nginx-autoinstall/commit/611d915eb6b6deae9c661d034a6f981191e75e1a and https://github.com/Angristan/nginx-autoinstall/commit/a057dff98d47ea1bac7e52f36ae3dae7243f5bbd
