### ISSUE TITLE
Brotli doesn´t work on Subdomains

### ISSUE THREAD

**Issue by benhartwich** [Angristan/nginx-autoinstall#44]
Hi,

thanks for providing this script. I´ve tried to use the brotli compression by installing nginx with your script, but brotli only works on main domains, not on any subdomain when defined at nginx.conf. 

When I set brotli at a subdomain vhost definition directly it´s also not working. Is this by design or is it because your script is missing anything?

**Comment by Angristan** [comment]
Hey, I think the problem is elsewhere for you.

In my nginx.conf:

```
brotli on;
brotli_comp_level 6;
brotli_types *;
```

I have not defined anything else for brotli.

Brotli is working:

```
user@server ~> curl -sILH "accept-encoding:gzip, deflate, br" https://mstdn.io/apple-touch-icon.png | grep Content-Encoding
Content-Encoding: br
user@server ~> curl -sILH "accept-encoding:gzip, deflate, br" https://munin.mstdn.io/localdomain/localhost.localdomain/df-day.png | grep Content-Encoding
Content-Encoding: br
```

**Comment by benhartwich** [comment]
Thanks, seems to be a local issue on one machine.
