### ISSUE TITLE
Empty_gif variable for Matomo

### ISSUE THREAD

**Issue by benhartwich** [Angristan/nginx-autoinstall#46]
Hi,

great script, but can you please insert a new module? The matomo vhost definition for nginx has an empty_gif variable (https://github.com/perusio/piwik-nginx/blob/master/apps/piwik/piwik.conf).

I had to implement the following module line at your script for using this variable: 
--with-http_image_filter_module
Also I needed to install the following package: libgd-dev

Can you please implement my suggestion?

Regards,

**Comment by Angristan** [comment]
This is a specific case, so no, please add your line manually (you can fork the repo too).

#41 will help you when it will be done
