### ISSUE TITLE
Support gzip

### ISSUE THREAD

**Issue by Sparki2002** [Angristan/nginx-autoinstall#51]
Hi,

I noticed, you're compiling nginx without gzip?
Is there any reason for this or can you add it?

**Comment by Angristan** [comment]
If you're talking about `ngx_http_gzip_module`, it's compiled by default.

**Comment by Sparki2002** [comment]
I'm trying to use static gzip

**Comment by Angristan** [comment]
Static gzip is rarely used, that's why it is not in the script. But you can easily add it yourself (one line) locally or make a fork. :)
