### ISSUE TITLE
Add support to read existing modules upon upgrade

### ISSUE THREAD

**Issue by uhlhosting** [Angristan/nginx-autoinstall#56]
Would be great to use same modules while upgrading a running nginx instance.

**Comment by Angristan** [comment]
What do you mean?

**Comment by uhlhosting** [comment]
For example reading of 
%nginx -V 
nginx version: nginx/1.2.2
built by gcc 4.2.1 20070719 
TLS SNI support enabled 
configure arguments: --prefix=/var/www --conf-path=/etc/nginx/nginx.conf --sbin-path=/usr/sbin/nginx --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-log-path=logs/access.log --error-log-path=logs/error.log --http-client-body-temp-path=/var/www/cache/client_body_temp --http-proxy-temp-path=/var/www/cache/proxy_temp --http-fastcgi-temp-path=/var/www/cache/fastcgi_temp --http-scgi-temp-path=/var/www/cache/scgi_temp --http-uwsgi-temp-path=/var/www/cache/uwsgi_temp --user=www --group=www --with-http_gzip_static_module --with-http_ssl_module --with-http_stub_status_module --with-ipv6 --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module
%

**Comment by Angristan** [comment]
I prefer not to do that, sorry.
