### ISSUE TITLE
centos

### ISSUE THREAD

**Issue by emobortnik** [angristan/nginx-autoinstall#58]
Hello!

I hope soon centos will be avaliable.

> # cat /tmp/nginx-autoinstall.log
> rm: cannot remove '/usr/local/src/nginx/': No such file or directory
> ./nginx-autoinstall.sh: line 116: apt-get: command not found
> ./nginx-autoinstall.sh: line 117: apt-get: command not found
>

**Comment by emobortnik** [comment]
just replaced apt-get with yum and it worked ;)

**Comment by angristan** [comment]
Not until a PR is submitted or I have the need to.
