### ISSUE TITLE
Display errors

### ISSUE THREAD

**Issue by PunKeel** [Angristan/nginx-autoinstall#6]
Use `2>/dev/null` instead of `&>/dev/null`

(oui j'aurai pu PR)

**Comment by Angristan** [comment]
C'est quoi la différence ? C'est une prise de tête les renvois comme ça :|

**Comment by PunKeel** [comment]
Evite de relancer le script sans >dev null, si des erreurs surviennent..
Autre solution: tout mettre dans un fichier /tmp/, et le supprimer si tout se passe bien :)
