### ISSUE TITLE
How to configure TLSv1.3 with nginx 1.15 ?

### ISSUE THREAD

**Issue by fefz** [angristan/nginx-autoinstall#60]
Use the latest script and set https successfully, but still display TlSv1.2 in Chrome & Firefox.
Part of config:
```
  # Certificate(s) and private key
  ssl_certificate /home/ssl/domain.crt;
  ssl_certificate_key /home/ssl/domain.key;

  # openssl dhparam 4096 -out /etc/ssl/dhparam.pem
  ssl_dhparam /home/ssl/dhparam.pem;

  ssl_protocols TLSv1.3 TLSv1.2 TLSv1.1 TLSv1;
  ssl_prefer_server_ciphers on;
  ssl_ciphers EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA512:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:ECDH+AESGCM:ECDH+AES256:DH+AESGCM:DH+AES256:RSA+AESGCM:!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS;

  ssl_session_cache shared:TLS:2m;
```

**Comment by angristan** [comment]
Did you try https://www.ssllabs.com/ssltest/?

**Comment by carlesjavierre** [comment]
I tried compiling nginx myself with this tool on the launch date of OpenSSL 1.1.1 (modifying the script) and applying a similar config (like the one you have there @fefz) and I wasn't successful in any way. Not even SSLLabs any other tool recognized TLS 1.3.

I think we need to dig deeper.

Did you get it working that way, @angristan?

**Comment by angristan** [comment]
Here is the config:

```nginx
ssl_protocols TLSv1.3 TLSv1.2;
ssl_ciphers TLS-CHACHA20-POLY1305-SHA256:TLS-AES-256-GCM-SHA384:TLS-AES-128-GCM-SHA256:EECDH+CHACHA20:EECDH+AESGCM:EECDH+AES;
```

`TLS-` can be `TLS13-`.

However, OpenSSL 1.1.1 was released with the final draft of TLS 1.3. SSLLabs and Chrome only support draft 28. 

When I tested the pre-release of 1.1.1, it was working, but not anymore, so that's why. We'll have to wait a bit for client support!

**Comment by carlesjavierre** [comment]
@angristan Oh, that's true. Didn't see that, now that I checked chrome's flags I see it.

Usually using [cipherli.st](https://cipherli.st/) 's ciphers, and they even say these are 1.3 compatible and (usually) safer (there are no CHACHA). Will test against SSLLabs when available. 

Thanks!

**Comment by fefz** [comment]
maybe can use this patch
https://github.com/hakasenyang/openssl-patch

**Comment by angristan** [comment]
Working with Chrome 70 as of today.

<img width="452" alt="screenshot 2018-10-31 at 23 02 39" src="https://user-images.githubusercontent.com/11699655/47822260-cb78ea00-dd63-11e8-8259-9175638c4594.png">

**Comment by dertin** [comment]
You can watch how it is installed here.
https://github.com/dertin/lemp-stack-debian
