### ISSUE TITLE
Compile nginx 1.14.0 failed: pagespeed issue

### ISSUE THREAD

**Issue by fconn** [angristan/nginx-autoinstall#61]
![default](https://user-images.githubusercontent.com/37580200/46232957-aca8c180-c379-11e8-8931-24530227c409.png)

Full `nginx-autoinstall.log` here: https://www.dropbox.com/s/xcrz8urpoajuhhi/nginx-autoinstall.log?dl=0

**Comment by angristan** [comment]
Seems you don't have enough RAM:

```log
cc: internal compiler error: Killed (program cc1plus)
```

**Comment by fconn** [comment]
Yeah, you're right... Checked `dmesg` and found 

`[22932002.461374] Out of memory in UB 14981: OOM killed process 30828 (cc1plus) score 0 vm:503352kB, rss:429372kB, swap:0kB`

Closing issue.

**Comment by angristan** [comment]
This is "common" issue. Compiling pagespeed on 512 MB of RAM is generally not sufficient, but 1 GB should do it
