### ISSUE TITLE
Patching of dynamic TLS records fail with Nginx 1.15.4

### ISSUE THREAD

**Issue by Karewan** [angristan/nginx-autoinstall#63]
When use the script by selecting Nginx 1.15.4, OpenSSL 1.1.1 and TLS Dynamic Records Support only, the patch fail.

The log file:

2018-09-29 09:57:04 (20.6 MB/s) - ‘nginx__1.11.5_dynamic_tls_records.patch’ saved [8243/8243]

patching file src/event/ngx_event_openssl.c
Hunk &#35;1 succeeded at 1267 (offset 136 lines).
Hunk &#35;2 succeeded at 2116 (offset 446 lines).
Hunk &#35;3 succeeded at 2258 (offset 452 lines).
patching file src/event/ngx_event_openssl.h
Hunk &#35;1 succeeded at 64 with fuzz 1 (offset 10 lines).
Hunk &#35;2 FAILED at 89.
Hunk &#35;3 succeeded at 116 (offset 18 lines).
1 out of 3 hunks FAILED -- saving rejects to file src/event/ngx_event_openssl.h.rej
patching file src/http/modules/ngx_http_ssl_module.c
Hunk &#35;1 succeeded at 246 with fuzz 1 (offset 13 lines).
Hunk &#35;2 succeeded at 611 (offset 43 lines).
Hunk &#35;3 succeeded at 683 (offset 45 lines).
Hunk &#35;4 succeeded at 881 with fuzz 1 (offset 49 lines).
patching file src/http/modules/ngx_http_ssl_module.h
Hunk &#35;1 succeeded at 58 (offset 1 line).

**Comment by angristan** [comment]
I guess it's not comptable anymore. It was made 2 years ago. I can't do anything about it so I'll remove it from the script

**Comment by nailarch** [comment]
The latest patch for latest nginx 1.15.8 is here - https://github.com/cloudflare/sslconfig/pull/102/commits/71b5cf3223e2f841ebdc019a781e4f6f2cfe6b17
