### ISSUE TITLE
Can you add Lua Module?

### ISSUE THREAD

**Issue by ktownmods** [angristan/nginx-autoinstall#65]
Can you add Lua?

**Comment by Firegarden** [comment]
[nginx-autoinstall.zip](https://github.com/angristan/nginx-autoinstall/files/2638603/nginx-autoinstall.zip)

Attached my Lua modified scripty bro

**Comment by ktownmods** [comment]
Thanks!

**Comment by angristan** [comment]
Thanks @Firegarden
