### ISSUE TITLE
GeoIP 2 support

### ISSUE THREAD

**Issue by Rathorian** [angristan/nginx-autoinstall#66]
Salut,

Je viens de m'apercevoir en utilisant ton script d'installation que GeoIP ne fonctionne pas et c'est normal.

Quand tu télécharges les deux fichiers GeoIP, tu les places dans "/usr/local/src/nginx/modules/geoip-db". Le problème c'est que tu les supprimes à la fin du script pour le nettoyage, sans déplacer le dossier "geoip-db" dans "/opt", comme indiquer dans le README.md

https://github.com/angristan/nginx-autoinstall/blob/08093bf0e6ec117cf479b83d4a54c92c47a44d55/nginx-autoinstall.sh#L193-L218

**Comment by Rathorian** [comment]
Salut,

Je te relance concernant l'issue.
C'est loin d'être grave mais comme je n'ai eu aucune réponse !

**Comment by Firegarden** [comment]
ngx_http_geoip2_module

**Comment by Rathorian** [comment]
@Firegarden 

Hi,

Maybe this part of the code is more or less absolute but not all!
The work that @angristan does is very good.

Propose him a PR with the new module ....

**Comment by Firegarden** [comment]
> @Firegarden
> 
> Hi,
> 
> Maybe this part of the code is more or less absolute but not all!
> The work that @angristan does is very good.
> 
> Propose him a PR with the new module ....

		# GeoIP2
		if [[ "$GEOIP" = 'y' ]]; then
			# Dependency
			add-apt-repository ppa:maxmind/ppa -y >> /tmp/nginx-autoinstall.log 2>&1
			apt update >> /tmp/nginx-autoinstall.log 2>&1			
			apt install libmaxminddb0 libmaxminddb-dev mmdb-bin >> /tmp/nginx-autoinstall.log 2>&1
						
			cd /usr/local/src/nginx/modules || exit 1
			git clone --recursive https://github.com/leev/ngx_http_geoip2_module >> /tmp/nginx-autoinstall.log 2>&1

			echo -ne "       Downloading GeoIP2 databases   [..]\\r"

			sudo mkdir -p /etc/nginx/geoip2/
			wget http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz >> /tmp/nginx-autoinstall.log 2>&1
			tar xaf GeoLite2-Country.tar.gz  --strip 1
			mv GeoLite2-Country.mmdb /etc/nginx/geoip2/
			
			wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz >> /tmp/nginx-autoinstall.log 2>&1
			tar xaf GeoLite2-City.tar.gz --strip 1
			mv GeoLite2-City.mmdb /etc/nginx/geoip2/	

			if [ $? -eq 0 ]; then
				echo -ne "       Downloading GeoIP2 databases   [${CGREEN}OK${CEND}]\\r"
				echo -ne "\\n"
			else
				echo -e "       Downloading GeoIP2 databases    [${CRED}FAIL${CEND}]"
				echo ""
				echo "Please look at /tmp/nginx-autoinstall.log"
				echo ""
				exit 1
			fi
		fi

Then in nginx modules line add

# GeoIP2
		if [[ "$GEOIP" = 'y' ]]; then			
			NGINX_MODULES=$(echo "$NGINX_MODULES"; echo "--add-module=/usr/local/src/nginx/modules/ngx_http_geoip2_module")
		fi

That will do it to change out and add support for geoip2

**Comment by angristan** [comment]
Added in https://github.com/angristan/nginx-autoinstall/commit/0bcd26424316c92eaa644a9cc48e93b64e6e7025
