### ISSUE TITLE
nginx.service: Failed to read PID from file /run/nginx.pid: Invalid argument

### ISSUE THREAD

**Issue by Rathorian** [angristan/nginx-autoinstall#67]
Salut,

Je pense qu'il y a un petit souci avec le fichier "nginx.service" pour systemd.
Avec la commande `service nginx status` j'ai une petite erreur : 

`systemd[1]: nginx.service: Failed to read PID from file /run/nginx.pid: Invalid argument`

Mais nginx tourne bien....

**Comment by angristan** [comment]
Ça semble être un bug connu sous Ubuntu : https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1581864

**Comment by Rathorian** [comment]
Effectivement et j'avoue ne pas avoir fait de recherche avant.

J'utilise Debian Stretch sur un VPS avec 1 CPU comme indiqué sur ton lien.

Sur diverses sources, ils donnent 2 solutions : 
1 - https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1581864/comments/3
2 - https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1581864/comments/7

Tu crois que tu pourrais en ajouter une ?

**Comment by Rathorian** [comment]
Pour information j'ai testé les deux solutions et la deuxième ne fonctionne pas.

La première fonctionne parfaitement, je n'ai plus d'erreur dans le status nginx.

**Comment by angristan** [comment]
C'est vraiment pas beau :( D'ailleurs quel OS utilises-tu ?

**Comment by Rathorian** [comment]
Je l'ai indiqué dans l'un de mes précédents messages mais je suis sous Debian 9.
J'utilise la version stable d'Nginx, donc la v1.14.1

Effectivement c'est pas très propre mais il y a pas beaucoup de solution, sachant que le bug à été décelé il y a plus de 2 ans.

**Comment by angristan** [comment]
Ah oui, merci, j'ai lu trop vite. C'est un VPS chez qui ? (OpenVZ ou une VM ?)

**Comment by Rathorian** [comment]
Un VPS de chez Hetzner

**Comment by angristan** [comment]
I updated the `nginx.service` from the Debian `nginx-common` package: https://github.com/angristan/nginx-autoinstall/commit/a3f4430c45e765d96eecb9798f8f02c2ccc30900

Fixed the pid path in `nginx.conf`: https://github.com/angristan/nginx-autoinstall/commit/7c21ac5da46f437e749bafe1d9b333be4c62db4b

And finally added the workaround: https://github.com/angristan/nginx-autoinstall/commit/1b7e6d7ffa394784b1ad024b481270fc65417fd7

Thanks for the report!
