### ISSUE TITLE
Problem to install Certbot

### ISSUE THREAD

**Issue by angelflo** [angristan/nginx-autoinstall#73]
Hi,
Please can someone try to help me to find a solution to install Certbot.
I installed Nginx thru your script (because I need pagespeed and brotlib), but because it block nginx packet in APT and certbot package have dependency with nginx package, i receive an error when I try to install the Certbot Nginx package ...
More info on https://github.com/certbot/certbot/issues/6362
If someone can help me to find a solution for this ... I'm not expert of Unix management.
Thanks a lot in advance.

**Comment by angristan** [comment]
See https://certbot.eff.org/lets-encrypt/debianother-other
