### ISSUE TITLE
Headless install

### ISSUE THREAD

**Issue by angristan** [angristan/nginx-autoinstall#78]
It would be great to export some variables and run the script without the menu

**Comment by treyssatvincent** [comment]
The way you have done the `read` isn't it already possible like this ?

~~~
OPTION=1 \
NGINX_VER=1 \
PAGESPEED=n \
BROTLI=n \
HEADERMOD=n \
GEOIP=n \
FANCYINDEX=n \
CACHEPURGE=n \
SSL=1 \
./nginx-autoinstall.sh
~~~

Do you want to only remove the menu interface if they are defined ?

**Comment by angristan** [comment]
Yes

**Comment by treyssatvincent** [comment]
I'm thinking of checking a `HEADLESS` variable before printing the menu, but what should happen if a variable isn't defined ? 

You'd prefer errors
~~~
case $NGINX_VER in
	1)
		NGINX_VER=$NGINX_STABLE_VER
	;;
	2)
		NGINX_VER=$NGINX_MAINLINE_VER
	;;
	*)
		echo "invalid/unspecified NGINX_VER"
		exit 1
	;;
esac
~~~

fallbacks
~~~
case $NGINX_VER in
	1)
		NGINX_VER=$NGINX_STABLE_VER
	;;
	2)
		NGINX_VER=$NGINX_MAINLINE_VER
	;;
	*)
		echo "invalid/unspecified NGINX_VER fallback to Stable $NGINX_STABLE_VER"
		NGINX_VER=$NGINX_STABLE_VER
	;;
esac
~~~

or default values
~~~
case $NGINX_VER in
	*)
		NGINX_VER=$NGINX_STABLE_VER
	;;
	2)
		NGINX_VER=$NGINX_MAINLINE_VER
	;;
esac
~~~

**Comment by angristan** [comment]
I think fallbacks would be the best.

**Comment by Cave-Johnson** [comment]
Could we also get a headless option to check the script is up to date?

**Comment by randomshell** [comment]
@Cave-Johnson you can use git instead of downloading the script directly.
`git clone https://github.com/angristan/nginx-autoinstall` to download and `git pull` to update.

**Comment by angristan** [comment]
Added by https://github.com/angristan/nginx-autoinstall/pull/80
