### ISSUE TITLE
Add option to remove systemctl actions

### ISSUE THREAD

**Issue by treyssatvincent** [angristan/nginx-autoinstall#79]
Sometime `systemctl` isn't available (for example in the official debian docker image).

Maybe this script could benefit of an option to remove the automatic enabling at installation and stop at uninstall.

**Comment by angristan** [comment]
The script is not designed to be run in a Docker container though? You should have all the steps in your Dockerfile and not call 3rd-party scripts

**Comment by treyssatvincent** [comment]
You're right, and I don't see any other use cases.
