### ISSUE TITLE
Add String of Options

### ISSUE THREAD

**Issue by zadro** [angristan/nginx-autoinstall#86]
I'm not too familiar with bash scripting and trying to add the following:

> --with-cc-opt='-m64 -march=native -DTCP_FASTOPEN=23 -g -O3'

But, this breaks the makefile.

Any ideas on how to add a line like that with an updated script?

**Comment by angristan** [comment]
Have you tried adding this line here? https://github.com/angristan/nginx-autoinstall/blob/0cd0ae5615c875ae45b4b11207e3e45b910b54d8/nginx-autoinstall.sh#L249

**Comment by zadro** [comment]
Yes, the script fails based on the first "space" in the line with single-quoted options. I think it's a bash file formatting issue.

**Comment by zadro** [comment]
I ended up adding any double-quoted options directly to the configure statement. My full process is here [https://stackoverflow.com/questions/55946939/trouble-with-spaces-in-bash-script-variable/](https://stackoverflow.com/questions/55946939/trouble-with-spaces-in-bash-script-variable/) and this issue can be closed.

**Comment by malikshi** [comment]
how is it? its work? im already enabled tfo but still cant use fastopen=number on nginx conf
