### ISSUE TITLE
Get versions from https://hg.nginx.org/nginx/ instead of hardcoding version.

### ISSUE THREAD

**Issue by VasiliyRusin** [angristan/nginx-autoinstall#88]
I think downloading the latest version from the repo is much better than hardcode the last version in the file.

**Comment by skid9000** [comment]
I don't think so...

Due to the fact that it is needed to check if every module is working correctly with the new version before pushing.

**Comment by panpansh** [comment]
yes and not, here we can lock a working version, the latest can break
