### ISSUE TITLE
Enhancement suggestion: Add ModSecurity module

### ISSUE THREAD

**Issue by angelflo** [angristan/nginx-autoinstall#98]
Hi,

Before all thanks a lot for your work on this nginx autoinstaller script.
Do you plan to integrate installation of ModSecurity Module in your nginx script ?
https://help.dreamhost.com/hc/en-us/articles/223608748-How-to-Install-libmodsecurity-nginx-on-Ubuntu-14-04
This module is a "must have" for many people to avoid hacking and now that it works on nginx I would like to implement it but I don't know how to do because nginx and other moduls are implemented thru your script.

Thanks again for all !

**Comment by tmiland** [comment]
Added with #104 :+1:

**Comment by angristan** [comment]
Done in #104
